### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jbenet** [ipfs/POST#1]
~~ Breaking Ground ~~

Milestone 1
- [ ] first draft of core spec (@jbenet, @mekarpeles) - https://github.com/ipfs/POST/issues/2
- [ ] first draft of blog ext spec 
- [ ] first draft of chat ext spec
- [ ] first draft of forum ext spec (@fazo96)
- [ ] list of other specs to read https://github.com/ipfs/POST/issues/3
- [ ] list of people/orgs to involve https://github.com/ipfs/POST/issues/4

**Comment by jbenet** [comment]
First large discussion about POST: https://github.com/ipfs/pm/issues/56#issuecomment-159116591

**Comment by tapaswenipathak** [comment]
Hi @jbenet: Where can I read about the current status of the implementation or research?

**Comment by Stebalien** [comment]
(@jbenet by proxy)

The work and thinking around POST ended up heavily influencing [IPLD](https://ipld.io). However, POST itself never made any significant progress.

At this point, the plan is to someday rebase this work on-top-of IPLD. However, that's a far-future task that isn't on anyone's radar at the moment.

**Comment by tapaswenipathak** [comment]
Hey @Stebalien, thanks for the information. :)
